"""init

Revision ID: fb9a52fc7306
Revises: 
Create Date: 2024-07-22 10:41:53.301952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9a52fc7306'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elecciones',
    sa.Column('Id_Eleccion', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('Hora_apertura', sa.Time(), nullable=False),
    sa.Column('Hora_cierre', sa.Time(), nullable=False),
    sa.Column('Pob_hab', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id_Eleccion')
    )
    op.create_table('frentes',
    sa.Column('IdFrente', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.Column('Imagen', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('IdFrente')
    )
    op.create_table('roles',
    sa.Column('IdRole', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('IdRole')
    )
    op.create_table('usuarios',
    sa.Column('CI', sa.Integer(), nullable=False),
    sa.Column('IdRole', sa.Integer(), nullable=False),
    sa.Column('Nombres', sa.String(length=100), nullable=False),
    sa.Column('Apellidos', sa.String(), nullable=False),
    sa.Column('Correo_electronico', sa.String(length=50), nullable=False),
    sa.Column('Estado_vzla', sa.String(length=50), nullable=False),
    sa.Column('Direccion_hab', sa.String(length=50), nullable=False),
    sa.Column('Direccion_electoral', sa.String(length=50), nullable=False),
    sa.Column('Fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('Telefono', sa.String(length=50), nullable=False),
    sa.Column('Imagen', sa.String(length=255), nullable=False),
    sa.Column('Habilitado', sa.Boolean(), nullable=False),
    sa.Column('Contrasena', sa.String(length=255), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['IdRole'], ['roles.IdRole'], ),
    sa.PrimaryKeyConstraint('CI')
    )
    op.create_table('candidatos',
    sa.Column('IdCandidato', sa.Integer(), nullable=False),
    sa.Column('IdFrente', sa.Integer(), nullable=False),
    sa.Column('IdEleccion', sa.Integer(), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['IdEleccion'], ['elecciones.Id_Eleccion'], ),
    sa.ForeignKeyConstraint(['IdFrente'], ['frentes.IdFrente'], ),
    sa.ForeignKeyConstraint(['IdUsuario'], ['usuarios.CI'], ),
    sa.PrimaryKeyConstraint('IdCandidato')
    )
    op.create_table('votos',
    sa.Column('IdVoto', sa.Integer(), nullable=False),
    sa.Column('IdEleccion', sa.Integer(), nullable=False),
    sa.Column('IdCandidato', sa.Integer(), nullable=False),
    sa.Column('IdVotante', sa.Integer(), nullable=False),
    sa.Column('Hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['IdCandidato'], ['candidatos.IdCandidato'], ),
    sa.ForeignKeyConstraint(['IdEleccion'], ['elecciones.Id_Eleccion'], ),
    sa.ForeignKeyConstraint(['IdVotante'], ['usuarios.CI'], ),
    sa.PrimaryKeyConstraint('IdVoto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('candidatos')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('frentes')
    op.drop_table('elecciones')
    # ### end Alembic commands ###
